# Generated by Django 2.1.7 on 2019-03-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.URLField(blank=True, help_text='Start URL with http://', max_length=255),
        ),
    ]
