# Generated by Django 2.1.7 on 2019-03-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190319_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(),
        ),
    ]
