# Generated by Django 2.1.7 on 2019-03-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190319_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(default='2019-03-19 20:00'),
        ),
    ]
